name: Fly Deploy
on:
  push:
    branches:
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  DEFAULT_BRANCH: master
  
jobs:
  deploy:
    if: ${{ github.event_name == 'push' && !contains(github.event.commits[0].message, '#skip') }}
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
  tag_release:
    needs: deploy
    name: Bump version and push tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: anothrNick/github-tag-action@bb4fa8ef27862a1335e74a97d5fa193e058ecd21
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch